# Generated by Django 5.2.11 on 2026-02-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sitesettings_default_replication_path'),
        ('common', '0004_sitesettings_connection_check_cache'),
    ]

    operations = [
    ]
