# Generated by Django 5.2.11 on 2026-03-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_merge_20260225_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='max_task_retries',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts for failed tasks before marking as failed.'),
        ),
    ]
