# Generated by Django 5.2.11 on 2026-02-24 08:08

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_set_superusers_admin_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.models.DBAutoUserManager()),
            ],
        ),
    ]
