# Generated by Django 5.2.11 on 2026-02-24 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label for this database', max_length=120)),
                ('db_type', models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('MYSQL', 'MySQL'), ('SQLITE', 'SQLite')], max_length=16)),
                ('host', models.CharField(help_text='Hostname / IP of the database server', max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('username', models.CharField(max_length=120)),
                ('encrypted_password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_frequency_minutes', models.PositiveIntegerField(default=60)),
                ('retention_days', models.PositiveIntegerField(default=7)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='hosts.database')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StorageHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(help_text='IP address or hostname of the SSH server', max_length=255)),
                ('ssh_port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(max_length=120)),
                ('encrypted_password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_hosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReplicationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_path', models.CharField(default='/backups', help_text='Remote directory on the SSH server', max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_policies', to='hosts.databaseconfig')),
                ('storage_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replication_policies', to='hosts.storagehost')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('database_config', 'storage_host')},
            },
        ),
    ]
