# Generated by Django 5.2.11 on 2026-02-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='backup_days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='Weekday numbers to run backups on (0=Mon … 6=Sun). Empty list means every day.'),
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='retention_keep_monthly_first',
            field=models.BooleanField(default=False, help_text='Keep all backups whose completed date falls on the 1st of any month.'),
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='retention_keep_weekly_day',
            field=models.IntegerField(blank=True, help_text='Keep backups created on this weekday (0=Mon … 6=Sun). Null = no exception.', null=True),
        ),
        migrations.AddField(
            model_name='replicationpolicy',
            name='last_replicated_at',
            field=models.DateTimeField(blank=True, help_text='Set by the independent scheduler after replication runs.', null=True),
        ),
        migrations.AddField(
            model_name='replicationpolicy',
            name='replication_frequency_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Run replication on this independent interval (minutes). Null = after every backup.', null=True),
        ),
        migrations.AddField(
            model_name='replicationpolicy',
            name='replication_retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Delete replicated copies older than this many days. Null = no separate retention.', null=True),
        ),
    ]
