# Generated by Django 5.2.11 on 2026-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_add_retention_exception_max_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(help_text='Actual database name', max_length=120),
        ),
    ]
